require: rubocop-rails

AllCops:
  NewCops: enable
  Exclude:
    - node_modules/**/*
    - tmp/**/*
    - vendor/**/*
    - .git/**/*
    - bin/*
    - Gemfile
    - db/migrate/**/*
    - db/schema.rb
    - db/seeds/*
    - lib/tasks/**/*
    - config/environments/**/*

Style/FrozenStringLiteralComment:
  Enabled: false

Style/NumericLiterals:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringHashKeys:
  Enabled: false

Style/MethodCallWithArgsParentheses:
  Enabled: false
  AllowParenthesesInChaining: true
  IgnoredMethods:
    - require
  Exclude:
    - spec/**/*

Style/BlockDelimiters:
  Exclude:
    - spec/**/*

Style/ClassAndModuleChildren:
  Enabled: false

Style/SymbolArray:
  EnforcedStyle: brackets

Style/Lambda:
  Enabled: false

Style/WordArray:
  Enabled: false

Metrics/ClassLength:
  CountAsOne: ['array', 'hash']

Metrics/MethodLength:
  CountAsOne: ['array', 'hash']
  Max: 20

Metrics/BlockLength:
  CountAsOne: ['array', 'hash']
  Exclude:
    - spec/**/*
    - config/routes.rb

Layout/LineLength:
  Enabled: false

Layout/EmptyLinesAroundAttributeAccessor:
  Enabled: true

Layout/MultilineMethodCallIndentation:
  Exclude:
    - spec/**/*

Layout/SpaceAroundMethodCallOperator:
  Enabled: true

Lint/BinaryOperatorWithIdenticalOperands:
  Enabled: false

Lint/AmbiguousBlockAssociation:
  Exclude:
    - spec/**/*

Lint/ConstantDefinitionInBlock:
  Exclude:
    - spec/**/*

Lint/DeprecatedOpenSSLConstant:
  Enabled: true

Lint/DuplicateElsifCondition:
  Enabled: true

Lint/DuplicateRescueException:
  Enabled: true

Lint/EmptyConditionalBody:
  Enabled: true

Lint/FloatComparison:
  Enabled: true

Lint/MissingSuper:
  Enabled: true

Lint/MixedRegexpCaptureTypes:
  Enabled: true

Lint/OutOfRangeRegexpRef:
  Enabled: true

Lint/RaiseException:
  Enabled: true

Lint/SelfAssignment:
  Enabled: true

Lint/StructNewOverride:
  Enabled: true

Lint/TopLevelReturnWithArgument:
  Enabled: true

Lint/UnreachableLoop:
  Enabled: true

Style/AccessorGrouping:
  Enabled: true

Style/ArrayCoercion:
  Enabled: true

Style/BisectedAttrAccessor:
  Enabled: true

Style/CaseLikeIf:
  Enabled: true

Style/ExplicitBlockArgument:
  Enabled: true

Style/ExponentialNotation:
  Enabled: true

Style/GlobalStdStream:
  Enabled: true

Style/HashAsLastArrayItem:
  Enabled: true

Style/HashEachMethods:
  Enabled: true

Style/HashLikeCase:
  Enabled: true

Style/HashTransformKeys:
  Enabled: true

Style/HashTransformValues:
  Enabled: true

Style/OptionalBooleanParameter:
  Enabled: true

Style/RedundantAssignment:
  Enabled: true

Style/RedundantFetchBlock:
  Enabled: true

Style/RedundantFileExtensionInRequire:
  Enabled: true

Style/RedundantRegexpCharacterClass:
  Enabled: true

Style/RedundantRegexpEscape:
  Enabled: true

Style/SingleArgumentDig:
  Enabled: true

Style/SlicingWithRange:
  Enabled: true

Style/StringConcatenation:
  Enabled: true

Rails/ActiveRecordCallbacksOrder:
  Enabled: true

Rails/FindById:
  Enabled: true

Rails/Inquiry:
  Enabled: true

Rails/MailerName:
  Enabled: true

Rails/MatchRoute:
  Enabled: true

Rails/NegateInclude:
  Enabled: false

Rails/Pluck:
  Enabled: true

Rails/PluckInWhere:
  Enabled: true

Rails/RenderInline:
  Enabled: true

Rails/RenderPlainText:
  Enabled: true

Rails/ShortI18n:
  Enabled: true

Rails/WhereExists:
  Enabled: true

Rails/UnknownEnv:
  Enabled: false
